name: Yolo Deploy

on:
  push:
    branches:
     - main
  pull_request:
      branches:
        - main

  workflow_dispatch:


env:
  REPO_URL: https://github.com/MajedSaade/YoloServiceFursa.git
  REPO_NAME: YoloServiceFursa

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.YOLO_EC2_HOST_DEV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host yolo
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Clone or Pull Code on EC2
        run: |
          ssh yolo "if [ -d ~/YoloServiceFursa ]; then cd ~/YoloServiceFursa && git pull; else git clone ${REPO_URL} ~/YoloServiceFursa; fi"

      - name: Run Deployment Script on EC2
        run: |
          ssh yolo "cd ~/YoloServiceFursa && bash deploy.sh"
